title: Keshav Bansal
author:
  name: Keshav Bansal
  email: keshavbansal015@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to my digital space, where I chronicle my adventures in technology and learning. 
  My goal is to regularly update this site with engaging blog posts, insightful book and paper reviews, and innovative project developments. 
  I hope that visitors to my website leave with a smile, having gained new knowledge and feeling inspired to explore and create. 
  Join me on this exciting journey of continuous growth and discovery!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KxBBB015
github_username:  keshavbansal015
linkedin_username: keshav-bansal-015

# Build settings
theme: minima
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
skin: auto

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - blogs.md
  # - bookshelf.md
  # - docushelf.md
  # - extra.md

date_format: "%b-%d-%Y"

# Generate social links in footer.
social_links:
  - platform: github
    user_url: "https://github.com/keshavbansal015/"
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/keshav-bansal-015/"
  - platform: x
    user_url: "https://twitter.com/KxBBB015"
  # - platform: devto
  #   user_url: "https://dev.to/keshavbansal015"
  #  - { platform: twitter,        user_url: "https://twitter.com/KxBBB015" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/testingposthere/" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/keshavbansal015" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/199791468@N07/" }

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       author: "KB"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# include:
#   - assets/images/